# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-08 00:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_reply_thread'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='slug',
            field=models.SlugField(default='', max_length=100, unique=True, verbose_name='Identificador'),
            preserve_default=False,
        ),
    ]
